### ISSUE TITLE
Zabbix template compatibility issue.

### ISSUE THREAD

**Issue by Tekchanddagar** [cavaliercoder/zabbix-template-convertor#10]
Hello Team,

We are using zabbix version `4.0.7` and want to monitor our postgresql DB over zabbix.
We followed the link [Postgresql monitoring using zabbix](https://github.com/zabbix/zabbix/tree/master/templates/db/postgresql)

But when we are trying to import the template we are getting error 
`Invalid tag "/zabbix_export/version": unsupported version number.`
Then i changed the zabbix version manually in template and replace 4.2 with 4.0 the i got below error:
```
Invalid tag "/zabbix_export/templates/template(1)": unexpected tag "tags".
```
When we tried to convert this template into zabbix version 4.0.7 using `zabbix-template-converter` we are getting error:
```
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-template-converter", line 343, in <module>
    __main__()
  File "/usr/local/bin/zabbix-template-converter", line 333, in __main__
    rule.apply()
  File "/usr/local/bin/zabbiYpx-template-converter", line 82, in apply
    raise ValueError('Unsupported output version: %s' % self.version)
ValueError: Unsupported output version: 4.0.7

```
You can download the template for version 4.2 from below link
[db template 4.2](https://git.zabbix.com/projects/ZBX/repos/zabbix/raw/templates/db/postgresql/template_db_postgresql.xml?at=refs%2Fheads%2Fmaster)
Can you please help me how we can convert zabbix 4.2 template into zabbix 4.0? 
Or any other way to monitor postgresql using zabbix?
Any help will be appreciated.

Thanks.

**Comment by Tekchanddagar** [comment]
Hello Team,
Can you please help me on above issue?

Thanks.

**Comment by Tekchanddagar** [comment]
Hello Team,

Can you please guide me?

Thanks.

**Comment by Tekchanddagar** [comment]
Hello Team,

I am still waiting for some guidance. Can you please help me?
Its last problem in my project.

Thanks.

**Comment by carceneaux** [comment]
Zabbix version 4.x is unsupported in this project. Your best bet is to either contribute the code to the project to fix this or convert the template manually.
