### ISSUE TITLE
Zabbix 3.4 Templates

### ISSUE THREAD

**Issue by scysys** [cavaliercoder/zabbix-template-convertor#4]
Please add support for Zabbix 3.4 Templates. So it can converted from 3.4 to 3.2 and so on

**Comment by ev0lvr** [comment]
bump this. thanks

**Comment by cavaliercoder** [comment]
I've started work on this. There are _a lot_ of changes the template structure in 3.4 so it may take some time!

**Comment by DavidMcGrathUnionStreet** [comment]
Good luck with the work, it will be so helpful :-)

**Comment by LordMrcS** [comment]
Just to add on this, from 3.4 to 3.0:

    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": unexpected tag "preprocessing".
    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": unexpected tag "jmx_endpoint".
    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": unexpected tag "master_item".
    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": the tag "multiplier" is missing.
    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": the tag "delta" is missing.
    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": the tag "formula" is missing.
    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": the tag "delay_flex" is missing.
    Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": the tag "data_type" is missing.
    Incorrect value "30s" for int field "delay".
    Incorrect value "90d" for int field "history".
    Incorrect value "365d" for int field "trends".

Fixed those manually and got it to import successfully.

**Comment by DanAlexson90** [comment]
Is this getting fixed in the release any time soon?

**Comment by cavaliercoder** [comment]
I'm sorry, I simply haven't been able to prioritize this issue. I may have to abandon my Zabbix projects soon, so anyone interested in maintaining and further developing this and other projects should chat with me!

**Comment by DanAlexson90** [comment]
That's unfortunate.

Second time I see a good Zabbix project being abandoned :\

Wishing luck

**Comment by te4336** [comment]
Zabbix is like going out and buying a really nice Ferrari at a great price only to get home and find out it's a pinto under the hood...

**Comment by ev0lvr** [comment]
You paid for zabbix?? It does what I need it to do.

**Comment by te4336** [comment]
We pay for the non-existent support if that’s what you mean...it’s by no means an enterprise monitoring solution. It may work for measuring the temps of your stash house but for us it’s pure shit

**Comment by ev0lvr** [comment]
I monitor an enterprise with it no issues. Sounds like you lack the skill
sets in your org to leverage an open source tool. Who pays for support for
an open source tool anyways? Look at solar winds, it installs on windows
and good support.

**Comment by LordMrcS** [comment]
In my company I use it to monitor a lot of variables in a lot of equipments scattered around my state and no issues here... Maybe you need expertise?

BTW, why this rant in this issue topic?

**Comment by te4336** [comment]
@ev0lvr Glad that it works for you at the local dispensary however your opinion of paying for support is seriously flawed. Any intelligent Enterprise that monitors the amount of hardware we do (1000+ physical nodes as well as 50k+ VM's) expects that there should be some sort of support unless it just simply isn't offered. Plenty of people pay for RedHat and Oracle Linux support but both of those can be downloaded as OSS. Has nothing to do with the skill set as I'm pretty sure our skill set within our org would be enough to devestate your Enterprise like a village filled with ISIS. And BTW SolarWinds costs millions for an org our size.

@LordMrcS Why is this rant located here? Let me count the ways...

1. Zabbix is probably the worst piece of software when it comes to compatibility. Just like the OP here was trying to create a converter tool it's a moot point as their core code changes with each release thus taking away any backwards compatibility. 

2. Support...jesus where do I begin here other than to say that Dell support from Bangalore scores a 10/10 when compared to their support. Between having to supply endless amounts of logs and output data as well as having to convert to a Latvian timezone only to be told that they don't know what's happening, that in itself is reason enough for someone to want to roll this raging dumpster fire of a monitoring solution down the road.

3. Enterprise ready...This is nowhere near enterprise ready. It's good enough to monitor and alert off of a couple hundred items but monitor millions items and things like scalability and management goes flying out the window faster than someone enjoying ev0lvr's stash. Saying that this is a great enterprise solution is literally like saying anal sex is great because it works on both genders.

4. Why is this rant here? Because you decided to respond back. When you don't use the solution in an actual enterprise (at least not by the sounds of it) who are you to criticize someone with a legitimate complaint? Kind of glad the OP abandoned his Zabbix projects as there are much better solutions he can move on to and support with his time and skills.

**Comment by ev0lvr** [comment]
Sorry guy but you are just plain wrong no matter how long your rant is.
Zabbix, nagios, tons of people use it and for very large orgs. If you can’t
figure it out like I said go pay for something that a bit easier for u to
figure out. Something more your “speed”

**Comment by LordMrcS** [comment]
4. I asked why you posted your rant here because you paid for support, that means logically one of zabbix channels would be the place to expose your demands. And I answered since you replied to an issue that I was auto subscribed and got a mail from it when you posted. Just like @ev0lvr there. And BTW It's just pointless to rant here since this whole project is abandoned as you stated. So my suggestion is, go ask for you money back at zabbix and pay for another company to do what you couldn't.

**Comment by cavaliercoder** [comment]
Zabbix is not perfect, but is the best Enterprise monitoring system I ever worked with, hands down. I have worked intimately with HP OM, Hitachi OM, SolarWinds, CA Spectrum, Microsoft SCOM, the usual OSS candidates like Elastic Search, Nagios, Cacti, etc. These were all deployed to thousands of hosts and some cost literally millions in licensing. None of them were able to deliver the business outcomes we got from Zabbix. Zabbix is _by all means_ a very competitive Enterprise solution.

Unfortunately, I don't get to work with Zabbix anymore, now that I work with an entirely bespoke monitoring toolchain. Projects like this one should be maintained by anyone in the Zabbix community willing to volunteer.

I'd be very grateful to anyone who can submit a PR to address this request for 3.4 and subsequently, 4.0 support.

**Comment by workshopit** [comment]
Just reading this dribble from **te4336**. It's quite hilarious actually.
We monitor 1000's of nodes using zabbix and is by far one of the best solutions out there and I've tried some of the "best" and most expensive.
I 100% agree with **ev0lvr**.
Guy, go pay for something if you don't have the skill set to manage such a comprehensive tool. But you're seriously missing the boat here

**Comment by Titan7777** [comment]
Hi
zabbix-template-converter -o 3.0 template_app_rabbitmq_service.xml > template_3.0_app_rabbitmq_service.xml
Applied: Template version string must be '3.0'
Applied: Document timestamp must be updated
Applied: HTTP Tests must not be exported before 3.2.0
How to fix ?"Applied: HTTP Tests must not be exported before 3.2.0"

**Comment by alexie83** [comment]
Hi, I'm getting the following error when attempting to convert a template, I wondered if anyone could please off some assistance:

`zabbix-template-converter -o 3.0 riello_ups_zabbix_5_template.xml > riello_ups_zabbix_3_template.xml 
Traceback (most recent call last):
  File "/home/aastachenko/.local/bin/zabbix-template-converter", line 343, in <module>
    __main__()
  File "/home/aastachenko/.local/bin/zabbix-template-converter", line 333, in __main__
    rule.apply()
  File "/home/aastachenko/.local/bin/zabbix-template-converter", line 74, in apply
    if self.versioncmp('3') < 0:
  File "/home/aastachenko/.local/bin/zabbix-template-converter", line 59, in versioncmp
    from pkg_resources import parse_version as V
ImportError: No module named pkg_resources`
