### ISSUE TITLE
Getting error when trying to convert 2.1 template to 3.0

### ISSUE THREAD

**Issue by mlawday** [cavaliercoder/zabbix-template-convertor#5]
Here is the command I'm trying to run: `zabbix-template-converter -o 3.0 template-pfsense21.xml > template-pfsense3.xml`

This is the error I'm getting:

Traceback (most recent call last):
  File "/bin/zabbix-template-converter", line 343, in <module>
    __main__()
  File "/bin/zabbix-template-converter", line 322, in __main__
    doc = ET.parse(args.file)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 42, column 91

I've also attached the template I'm trying to convert

**Comment by hlovdal** [comment]
This tool is only for downgrading (e.g. 2.1 to 3.0) and not the other way around.
